# تكليفات الدروس من الدرس 019 إلى 020

# التكليف 01
T1 = 10
T2 = 10.22
T3 = 3+5J 
print(type(T1))
print(type(T2))
print(type(T3))


# التكليف 02
num = 1+2j

# طباعة الجزء الخيالي (Imaginary Part)
print(num.imag)
# طباعة الجزء الحقيقي (Real Part)
print(num.real) 


# التكليف 03
num = 10
print(f'{num:10f}')


# التكليف 04
num = 159.650 
print(int(num))
print(type(int(num)))


# التكليف 05
# 100 - 115 = -15
# 50 * 30 = 1500
# 21 % 4 = 1
# 110 / 11 = 10
# 97 // 20 = 4


